/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ERC721AIERC721ReceiverUpgradeable,
  ERC721AIERC721ReceiverUpgradeableInterface,
} from "../ERC721AIERC721ReceiverUpgradeable";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onERC721Received",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ERC721AIERC721ReceiverUpgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): ERC721AIERC721ReceiverUpgradeableInterface {
    return new utils.Interface(
      _abi
    ) as ERC721AIERC721ReceiverUpgradeableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC721AIERC721ReceiverUpgradeable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ERC721AIERC721ReceiverUpgradeable;
  }
}
