/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IndelibleContract,
  IndelibleContractInterface,
} from "../IndelibleContract";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "count",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
];

export class IndelibleContract__factory {
  static readonly abi = _abi;
  static createInterface(): IndelibleContractInterface {
    return new utils.Interface(_abi) as IndelibleContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IndelibleContract {
    return new Contract(address, _abi, signerOrProvider) as IndelibleContract;
  }
}
